import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className="h-screen p-4">{children}</body>
    </html>
  );
}
