import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";
import { Navbar } from "@/ui/components/common/Navbar";
import { Footer } from "@/ui/components/common/Footer";

export const metadata: Metadata = {
  title: "Next Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" data-theme="light">
        <body>
          <Navbar />
          <main className="container mx-auto p-8">{children}</main>
          <Footer />
          {modal}
        </body>
      </html>
    </ClerkProvider>
  );
}
