import type { Metadata } from "next";
import "./globals.css";

import { Navbar } from "@/ui/organisms/Navbar";
import { Footer } from "@/ui/organisms/Footer";

export const metadata: Metadata = {
  title: "Next Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <Navbar />
        <main className="h-full">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
